services:

  controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  controllers.TasksPutController:
    class: ../../controllers/TasksPutController
    arguments: ["@TaskCreator"]

  controllers.TaskListGetController:
    class: ../../controllers/TaskListGetController
    arguments: ["@TasksFinder"]